USERS = [
    ["root", "1"],
    ["admin", "P@ssw0rd"],
    ["user", "%1"],
    ["user2", "Password$1"],
    ["johnsmith", "S3cur3P@ss"],
    ["user123", "MyP@ssw0rd"],
    ["cooluser", "P@ssw0rd123"],
    ["jdoe", "Secret123"],
    ["testuser", "P@ssword!"],
    ["newuser", "MySecretP@ss"],
    ["awesomeuser", "P@ssw0rd987"],
    ["user2022", "Secure123!"],
    ["webmaster", "P@ssw0rd2022"],
    ["guest", "Guest123"],
    ["techguru", "P@ssw0rdTech"],
    ["devuser", "P@ssw0rdDev"],
    ["user01", "Password123!"],
    ["adminuser", "AdminP@ssw0rd"],
    ["user2023", "NewYear2023"],
    ["securityuser", "SecureP@ssw0rd"],
    ["user007", "SecretAgent!"],
    ["hellouser", "Hello123"],
    ["pythonuser", "PythonP@ss"],
]
